[*,production,staging,testing,development]
; --- documents ---
documents.storages.100.submodule = "\Numbers\Users\Documents\Drivers\LocalFolder\Base"
documents.storages.100.name = "Local Folder"
documents.storages.100.dir = "/Users/Development/domains/com.card-fools/application/storage/documents/"

; AWS storage
documents.storages.200.submodule = "\Numbers\Users\Documents\Drivers\Amazon\Base"
documents.storages.200.name = "AWS S3"

documents.default.storage = "aws"
documents.default.temp_dir = "/Users/Development/domains/com.card-fools/application/storage/documents/temp/"
