
[*,production,staging,testing,development]
; template settings
application.template.name = "default"
application.template.available.0 = "default"
application.template.available.1 = "blank"
application.template.available.2 = "iframe"
application.template.available.3 = "no_styles"

; default layout
application.layouts.default.name = "Numbers Applications"
application.layouts.default.layout_type = "php"
application.layouts.default.layout_path = "/Layout/RevealB5.template.php"
application.layouts.default.email_type = "php"
application.layouts.default.email_path = "/Layout/RevealEmail.template.php"
application.layouts.default.title = "default"
application.layouts.default.menu = "default"
application.layouts.default.popup_menu = true
application.layouts.default.footer = "default"
application.layouts.default.extra_forms = "default"
application.layouts.default.site = "vite_react_ts_6_2_0"

; blank layout
application.layouts.blank.name = "Numbers Applications: blank layout"
application.layouts.blank.layout_type = "php"
application.layouts.blank.layout_path = "/Numbers/Templates/Common/Layout/BlankLayout.template.php"
application.layouts.blank.email_type = "php"
application.layouts.blank.email_path = "/Numbers/Templates/Presets/Bootstrap5/Layout/BlankEmail.template.php"
application.layouts.blank.title = "default"
application.layouts.blank.menu = "default"
application.layouts.blank.popup_menu = false
application.layouts.blank.footer = "default"
application.layouts.blank.extra_forms = "default"
application.layouts.blank.site = "vite_react_ts_6_2_0"

; no styles layout
application.layouts.no_styles.name = "Numbers Applications: no styles layout"
application.layouts.no_styles.layout_type = "php"
application.layouts.no_styles.layout_path = "/Numbers/Templates/Common/Layout/NoStylesLayout.template.php"
application.layouts.no_styles.email_type = "php"
application.layouts.no_styles.email_path = "/Numbers/Templates/Presets/Bootstrap5/Layout/BlankEmail.template.php"
application.layouts.no_styles.title = "no_styles"
application.layouts.no_styles.menu = "no_styles"
application.layouts.no_styles.popup_menu = false
application.layouts.no_styles.footer = "no_styles"
application.layouts.no_styles.extra_forms = "no_styles"
application.layouts.no_styles.site = "vite_react_ts_6_2_0"

; iframe layout
application.layouts.iframe.name = "Numbers Applications: Iframe"
application.layouts.iframe.layout_type = "php"
application.layouts.iframe.layout_path = "/Layout/RevealIframe.template.php"

[development]
; template settings, legacy template set to false
;application.layout.use.layouts = true