[*,production,staging,testing,development]
flag.global.sms.delivery.submodule = "\Numbers\Backend\SMS\Twilio\Base"
flag.global.sms.delivery.account_sid = ""
flag.global.sms.delivery.auth_token = ""
flag.global.sms.delivery.from = ""
flag.global.sms.delivery.name = ""

; --- require profile to use the service ---
flag.global.sms.delivery.require_profile = 1

[development]
debug.override_phone = ""
