[*,production,staging,testing,development]
flag.global.sms.delivery.submodule = "\Numbers\Backend\SMS\Twilio\Base"
flag.global.sms.delivery.account_sid = "ACe70b959e03b0df02d284996caddf6a52"
flag.global.sms.delivery.auth_token = "b6c47df0639271538b440c35a24d3fc5"
flag.global.sms.delivery.from = "+13656546869"
flag.global.sms.delivery.name = "Card Fools"

; --- require profile to use the service ---
flag.global.sms.delivery.require_profile = 1

[development]
debug.override_phone = "+14167102135"
