[*,production,staging,testing,development]
flag.global.mail.delivery.submodule = "\Numbers\Backend\Mail\PHPMailer\Base"
flag.global.mail.delivery.smtp.host = "email-smtp.ca-central-1.amazonaws.com"
flag.global.mail.delivery.smtp.port = 587
flag.global.mail.delivery.smtp.auth = 1
flag.global.mail.delivery.smtp.username = "AKIA5OFB6DCOH7CQ26UJ"
flag.global.mail.delivery.smtp.password = "BDQG7KwWdoLJP19ADGbKy+10SRGHRCFQyFFiOTdemPYg"
flag.global.mail.delivery.smtp.secure = "tls"

[development]
debug.override_email = "volodymyr.volynets@gmail.com" ; overrides for Mail classes
;debug.mail_smtp = true
