[*,production,staging,testing,development]
flag.global.mail.delivery.submodule = "\Numbers\Backend\Mail\PHPMailer\Base"
flag.global.mail.delivery.smtp.host = "email-smtp.ca-central-1.amazonaws.com"
flag.global.mail.delivery.smtp.port = 587
flag.global.mail.delivery.smtp.auth = 1
flag.global.mail.delivery.smtp.username = ""
flag.global.mail.delivery.smtp.password = ""
flag.global.mail.delivery.smtp.secure = "tls"

[development]
debug.override_email = "" ; overrides for Mail classes
;debug.mail_smtp = true
