[*,production,staging,testing,development]
developer.name = ""
developer.email = ""

; --- debug ---
debug.email = "" ; errors would be sent to this email address

[development]
debug.super_user.password = ""
debug.super_user.ips.0 = "127.0.0.1"

debug.send_all_errors = true
