[*,production,staging,testing,development]
; --- logs ---
log.default.submodule = "\Numbers\Backend\Log\Db\Base"
log.default.autoconnect = 1
log.default.cc.0 = "file"

log.email.submodule = "\Numbers\Backend\Log\Mail\Base"
log.email.autoconnect = 1
log.email.email = "volodymyr.volynets@gmail.com"

log.file.submodule = "\Numbers\Backend\Log\File\Base"
log.file.autoconnect = 1
log.file.logs.dir = "/Users/Development/domains/com.card-fools/logs/"
log.file.sql.dir = "/Users/Development/domains/com.card-fools/logs/"

log.settings.slow_sql_seconds = 3.00
log.settings.slow_cache_seconds = 1.00
log.settings.slow_request_seconds = 5.00

[development]
log.default.db.enabled = 1
log.file.logs.enabled = 1
log.file.sql.enabled = 0
