[*,production,staging,testing,development]
; sites settings
application.sites.vite_react_ts_6_2_0.name = "vite_react_ts_6_2_0"
application.sites.vite_react_ts_6_2_0.title = "Vite 6.2.0"
application.sites.vite_react_ts_6_2_0.model.enabled = false
application.sites.vite_react_ts_6_2_0.model.dir = "root://public_sites/vite_react_ts_6_2_0/src/Numbers"
application.sites.vite_react_ts_6_2_0.model.public_dir = "root://public_sites/vite_react_ts_6_2_0/public"
application.sites.vite_react_ts_6_2_0.model.types.0 = "\Object\Table"
application.sites.vite_react_ts_6_2_0.model.types.1 = "\Object\ActiveRecord"
application.sites.vite_react_ts_6_2_0.view.enabled = true
application.sites.vite_react_ts_6_2_0.view.dir = "root://public_sites/vite_react_ts_6_2_0/src/Numbers"
application.sites.vite_react_ts_6_2_0.view.dir_prefix = "./../"
application.sites.vite_react_ts_6_2_0.view.type = "react"
application.sites.vite_react_ts_6_2_0.i18n.enabled = true
application.sites.vite_react_ts_6_2_0.i18n.dir = "root://public_sites/vite_react_ts_6_2_0/src/Numbers"
application.sites.vite_react_ts_6_2_0.manifest = "deployment://public_html/VRT/.vite/manifest.json"
application.sites.vite_react_ts_6_2_0.public_dir = "/VRT/"
